### ISSUE TITLE
[WARN] No ENV file found

### ISSUE THREAD

**Issue by will-stone** [csepulv/electron-with-create-react-app#1]
Thanks for the blog post and this repo! After I `run dev` (I'm using Yarn but it happens with NPM too), I get the warning `No ENV file found`. Should I add one? What's your suggestion here?

**Comment by clarksandholtz** [comment]
I had this exact same problem. Even after adding the .env file, it didn't work for me

**Comment by csepulv** [comment]
There is no .env file required. I am pretty sure `node-foreman` is generating the warning. If you run the commands in the Profile file independently (in two different console/terminal windows), you won't see the warning.

If I create an empty `.env` file in the project root directory, the warning no longer appears. 

But in any event, a `.env` file is not required.
