### ISSUE TITLE
[WARN] Cannot read property '1' of null

### ISSUE THREAD

**Issue by gehnster** [csepulv/electron-with-create-react-app#11]
When I run npm start I get the following error. I'm running on a windows machine. Far as I can tell my setup is exactly the same as this branch.

[WARN] Cannot read property '1' of null

**Comment by csepulv** [comment]
Is that the only error? Is there a full log trace? I don't have any ideas and would more info to try to help.

**Comment by gehnster** [comment]
That is unfortunately all it tells me. It just starts looping itself too weirdly. I think it has to be a foreman issue but I haven't a clue what the foreman issue is exactly. I also have to think it has to do with the foreman setup because if I run react-start and electron-start on their own it works fine.

`Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\app>npm start

> tavern-tale-app@0.1.0 start C:\app
> nf start -p 3000

[OKAY] Loaded ENV .env File as KEY=VALUE Format
[WARN] Cannot read property '1' of null
[OKAY] package.json file found - trying 'npm start'
12:29:44 PM web.1 |  > app@0.1.0 start C:\app
12:29:44 PM web.1 |  > nf start -p 3000
12:29:44 PM web.1 |  [OKAY] Loaded ENV .env File as KEY=VALUE Format
12:29:44 PM web.1 |  [WARN] Cannot read property '1' of null
12:29:44 PM web.1 |  [OKAY] package.json file found - trying 'npm start'
12:29:45 PM web.1 |  12:29:45 PM web.1 |  > app@0.1.0 start C:\app
12:29:45 PM web.1 |  12:29:45 PM web.1 |  > nf start -p 3000
12:29:46 PM web.1 |  12:29:46 PM web.1 |  [OKAY] Loaded ENV .env File as KEY=VALUE Format
12:29:46 PM web.1 |  12:29:46 PM web.1 |  [WARN] Cannot read property '1' of null
12:29:46 PM web.1 |  12:29:46 PM web.1 |  [OKAY] package.json file found - trying 'npm start'
12:29:47 PM web.1 |  12:29:47 PM web.1 |  12:29:47 PM web.1 |  > app@0.1.0 start C:\app
12:29:47 PM web.1 |  12:29:47 PM web.1 |  12:29:47 PM web.1 |  > nf start -p 3000
12:29:47 PM web.1 |  12:29:47 PM web.1 |  12:29:47 PM web.1 |  [OKAY] Loaded ENV .env File as KEY=VALUE Format
12:29:47 PM web.1 |  12:29:47 PM web.1 |  12:29:47 PM web.1 |  [WARN] Cannot read property '1' of null
12:29:47 PM web.1 |  12:29:47 PM web.1 |  12:29:47 PM web.1 |  [OKAY] package.json file found - trying 'npm start'
12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  > app@0.1.0 start C:\app
12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  > nf start -p 3000
12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  [OKAY] Loaded ENV .env File as KEY=VALUE Format
12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  [WARN] Cannot read property '1' of null
12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  12:29:49 PM web.1 |  [OKAY] package.json file found - trying 'npm start'
12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  > app@0.1.0 start C:\app
12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  > nf start -p 3000
12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  [OKAY] Loaded ENV .env File as KEY=VALUE Format
12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  [WARN] Cannot read property '1' of null
12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  12:29:50 PM web.1 |  [OKAY] package.json file found - trying 'npm start'
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  > app@0.1.0 start C:\app
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  > nf start -p 3000
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [OKAY] Loaded ENV .env File as KEY=VALUE Format
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [WARN] Cannot read property '1' of null
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [OKAY] package.json file found - trying 'npm start'
[WARN] Interrupted by User
[DONE] Killing all processes with signal  SIGINT
Terminate batch job (Y/N)? 12:29:52 PM web.1 |  [WARN] Interrupted by User
12:29:52 PM web.1 |  [DONE] Killing all processes with signal  SIGINT
12:29:52 PM web.1 |  12:29:52 PM web.1 |  [WARN] Interrupted by User
12:29:52 PM web.1 |  12:29:52 PM web.1 |  [DONE] Killing all processes with signal  SIGINT
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [WARN] Interrupted by User
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [DONE] Killing all processes with signal  SIGINT
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [WARN] Interrupted by User
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [DONE] Killing all processes with signal  SIGINT
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [WARN] Interrupted by User
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [DONE] Killing all processes with signal  SIGINT
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  ^C
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [WARN] Interrupted by User
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  [DONE] Killing all processes with signal  SIGINT
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 Exited with exit code null
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 Exited with exit code null
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 Exited with exit code null
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 Exited with exit code null
12:29:52 PM web.1 |  12:29:52 PM web.1 |  12:29:52 PM web.1 Exited with exit code null
12:29:52 PM web.1 |  12:29:52 PM web.1 Exited with exit code null
12:29:52 PM web.1 Exited with exit code null
`

**Comment by csepulv** [comment]
it seems you are getting a warning, not an error. Do things start okay? 
Do you have a .env file in the main directory? It isn't necessary, but it might clear the warning. It can be empty.

**Comment by gehnster** [comment]
I have a .env file for sure, but it is empty. Thinks don't start ok at all, the above code lines are from when I use npm start. Yes I get what I listed was an error but as you mentioned it doesn't give any other details so I'm not sure how to debug. :( The only thing I can think of being different between what the original post had for this setup and what I'm using is that I am Windows based.

**Comment by csepulv** [comment]
Don't use 'npm start'. The medium post notes to use 'npm run dev'

Or use this [branch](https://github.com/csepulv/electron-with-create-react-app/tree/npm-start), which uses 'npm start'

**Comment by gehnster** [comment]
I'm using the branch that uses npm start
