### ISSUE TITLE
CSS hotreload

### ISSUE THREAD

**Issue by ojacquemart** [csepulv/electron-with-create-react-app#18]
Hello,

Great project 👍 

The hot reload app is working fine with js files but it does not work with the css files.
Any idea to make the hot reload working?

**Comment by csepulv** [comment]
Which css files don't reload? I tried making changes to App.css and index.css and they reload. (As a note, `create-react-app` doesn't technically have hot reloading, but just reloading. (https://github.com/facebook/create-react-app/pull/2304)
