### ISSUE TITLE
Trying to use rethinkdb

### ISSUE THREAD

**Issue by ivanthemeh** [csepulv/electron-with-create-react-app#21]
I am trying to use rethinkdb in this starter and I am getting the error: 
```
   bluebird.js:953 Unhandled rejection Error: Failed to execute 'open' on 'XMLHttpRequest': Invalid URL
   at new HttpConnection 
   (http://localhost:3000/static/js/bundle.js:31218:10)
```
any help would be appreciated. Thanks!

**Comment by csepulv** [comment]
Unfortunately I don't know. I am guessing the connection url for rethinkdb might be invalid, but it is hard to say. What else do you see in the logs or via debugging?

**Comment by ivanthemeh** [comment]
it happens with a basic install and connection of rethink.  I would love to get this working but I have no idea how to debug this..

**Comment by csepulv** [comment]
Unfortunately I am not sure. I haven't used `rethinkdb`. I would try to walkthrough in a debugger (Visual Studio or Webstorm, for example) or add some log statements to verify the urls. The log doesn't indicate the reason 'open' failed.

**Comment by csepulv** [comment]
how are you starting the app? `npm run dev` (as noted in the article) or `npm start`?  if you are using `npm start`, Chrome will probably load. `npm run dev` should not open Chrome. But if you are using `npm run dev`, then I don't know why Chrome is loading.

**Comment by ivanthemeh** [comment]
You think that could be causing the issue?

**Comment by ivanthemeh** [comment]
Dang I was really hoping to use this as a starter as opposed to electron-react-boilerplate but If I cant get this to work I wont be able to. 

I am not able to run this without it opening a window in chrome... Do you think that is what is causing the connect function issue? 

Please and Thanks!

**Comment by csepulv** [comment]
I am not sure. I also don't know if the chrome window is the cause of the problem. To diagnose, I would start with a clean install of the repo and confirm only the electron window (and not Chrome) loads. 
I just did ...
```
git clone https://github.com/csepulv/electron-with-create-react-app.git
cd electron-with-create-react-app/
npm install
npm run dev
```
and the starter app runs in electron without loading a Chrome window. If that doesn't work, then something else is happening in your environment. If it does work, it might help diagnose what else changed as you add `rethinkdb`
