### ISSUE TITLE
[REQUEST] electron-packager configuration

### ISSUE THREAD

**Issue by erikfox** [csepulv/electron-with-create-react-app#3]
I'm new to Electron/desktop apps coming from a React/web app background. I've started writing an application based on your boilerplate but I haven't been able to get [electron-packager](https://github.com/electron-userland/electron-packager) to build the actual `.app` executable.

Have you accomplished that for this repo and do you have any plans to add those instructions to the blog post?

**Comment by csepulv** [comment]
What did you do to build the package? 

My tutorial was mostly about bootstrapping, so I hadn't planned on adding packaging instructions.

That said, I tried to quickly build a package. I needed to build the app first, `npm run build`, and then I ran
```electron-packager . MyApp --out=dist/osx --platform=darwin --arch=x64```
(you would set whatever flags you need)

This created a `.app` file that I could run.

Can you tell me a little more about what errors are getting? Or maybe try the above and let me know if it doesn't work.

**Comment by vicentedealencar** [comment]
Hi, I got the .exe with [electron-builder](https://github.com/electron-userland/electron-builder). Check out [this commit](https://github.com/vicentedealencar/electron-with-create-react-app/commit/f1729381d588e65ac140ce5a08cc6277babd9641).

**Comment by csepulv** [comment]
cool.

**Comment by vicentedealencar** [comment]
I could open a PR, but i guess I screwed it up adding yarn. Not sure if you are into it, though I don't think there is a way not to. Up to you, @csepulv

**Comment by csepulv** [comment]
I think it is okay to not do a PR. There are various electron packagers, so it might be better to not pick one for the tutorial, which is focussed on setup. You included a pointer to your fork, so that will hopefully help those using electron-builder.

**Comment by hawkins** [comment]
@vicentedealencar 's `electron-builder` setup commit worked beautifully for me, but it may be handy to add a link to it in the readme, like you've done for the logging capture branch, for visitors who don't think to search the GitHub issues 🙂

**Comment by csepulv** [comment]
done

**Comment by Nick-the-BinaryTree** [comment]
Hey, did anyone else encounter the issue where if they try to run `npm run build` before using electron-packager, the `window.require` statements cause an error because they are not recognized?

I tried switching them out with normal `require` statements with a try-catch, but that just took me forward to an error in the uglifier the create-react-app build script was using.

Any suggestions? I should be using `npm run build` before packaging right?
[Here's the small repo of the ebook reader I'm working on.](https://github.com/Nick-the-BinaryTree/readtron)

**Comment by csepulv** [comment]
I would take a look at the work @vicentedealencar did. It is [here](https://github.com/vicentedealencar/electron-with-create-react-app/commit/f1729381d588e65ac140ce5a08cc6277babd9641)
