### ISSUE TITLE
window.require doesn't work with latest version of electron

### ISSUE THREAD

**Issue by whmountains** [csepulv/electron-with-create-react-app#30]
https://github.com/csepulv/electron-with-create-react-app/blob/7d7f0f307cc77aa94d4d592ab7a1d9b8b1edacde/src/electron-starter.js#L16

The latest version of electron has `nodeIntegration` disabled by default, causing `window.require` to not work.

To fix this:

```js
mainWindow = new BrowserWindow({
  width: 800,
  height: 600,
  webPreferences: { nodeIntegration: true },
})
```

**Comment by csepulv** [comment]
Thanks for the tip. I've made the change.
