### ISSUE TITLE
Module not found: 'child_process'

### ISSUE THREAD

**Issue by FJiskra** [csepulv/electron-with-create-react-app#32]
Hello,

can not use shelljs dependency with your app. Getting this error:

Failed to compile.

Error in ./~/shelljs/src/exec.js
Module not found: 'child_process'

Is there way to fix that?

to replicate: 
`git clone git@github.com:csepulv/electron-with-create-react-app.git errReport && cd errReport && npm i && npm i shelljs`

then add this line to render method of App.js:
`let shell = require('shelljs');`

then `npm run dev`

**Comment by csepulv** [comment]
I am sorry, I don't know what is going on. I haven't used shelljs and unfortunately I don't have time to try to reproduce and debug.

Have you tried pulling the require statement out of render and putting at the top of the file? Did Google not turn up anything?

**Comment by FJiskra** [comment]
I figured that there are missing env variables in process.env. No suggestions from google helped.
I am now using this repository: https://github.com/electron-react-boilerplate/electron-react-boilerplate
It does the same thing, but it has less bugs. Child_process module loads properly.

**Comment by csepulv** [comment]
I am glad you found a path that works for you
