### ISSUE TITLE
How do we run this in production?

### ISSUE THREAD

**Issue by maayanalbert** [csepulv/electron-with-create-react-app#33]
Thanks for the article! How should we deploy this/ run it in production?

**Comment by csepulv** [comment]
I suggest looking at https://github.com/electron-userland/electron-builder or https://github.com/electron/electron-packager. I've used both and they are pretty popular for packaging an application for distribution/installation.

https://github.com/vicentedealencar/electron-with-create-react-app/commit/f1729381d588e65ac140ce5a08cc6277babd9641 shows an example with `electron-builder`
