### ISSUE TITLE
Hello,I want to know how can  I update the ico of the packaged .exe file for the electron package

### ISSUE THREAD

**Issue by Flyooofly** [csepulv/electron-with-create-react-app#41]
![image](https://user-images.githubusercontent.com/31236750/120642042-fb05ab00-c4a6-11eb-8fa0-104885dd1a56.png)
I want to change this default ico for the .exe file,please tell me wher to change this ico file,thankyou

**Comment by csepulv** [comment]
It depends on your packager, I think. For example, with electron builder, see [https://www.electron.build/icons](https://www.electron.build/icons)

**Comment by Flyooofly** [comment]
Thank you for the ideas.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "csepulv/electron-with-create-react-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月3日(星期四) 晚上11:26
***@***.***&gt;;
抄送:&nbsp;"2207326681"<2207326681@***@***.***&gt;;
主题:&nbsp;Re: [csepulv/electron-with-create-react-app] Hello,I want to know how can  I update the ico of the packaged .exe file for the electron package (#41)





 
It depends on your packager, I think. For example, with electron builder, see https://www.electron.build/icons
