### ISSUE TITLE
Running express server as part of electron app

### ISSUE THREAD

**Issue by nikhilag** [csepulv/electron-with-create-react-app#9]
I have a server electron app to which all client apps connect. I had to do this because the customer wants the server running within their premises. I created an express server in the following way:-
1) Created a server.js file inside public directory where I run the express server.
2) Created a server.html which is loaded in a new hidden browser window from electron.js. The server.html simply runs a function with `require('.\server')`. **I get an error here saying that the required module was not found. I don't know why since server.html and server.js are right next to each other.** %PUBLIC_URL% won't work here since server.html is loaded after the build step and during the electron step.

What can I do to fix this issue? Is there a better way of running an express server with create-react-app for electron?

**Comment by csepulv** [comment]
I think you need to run the express server on its, not from within the electron application. You can use [node-foreman](https://github.com/strongloop/node-foreman) to help setup multiple processes in development, but basically you need to manage/develop your server as its own application.

**Comment by nikhilag** [comment]
Thanks @csepulv.

However, I did manage to get the server running by using the following code in server.html:-

```
    <script>
        (function(){
            let {remote} = require('electron');
            let path = require('path');
            let appPath = remote.app.getAppPath();
            require(path.resolve(appPath, 'public/nodeServer/graphqlServer.js'));
        }());
    </script>
```
Is there any disadvantage of running server inside an electron app? My reason for doing this is to allow auto updates to server and to make it easy for client to set it up.

**Comment by csepulv** [comment]
I would imagine you have multiple users, in which case I think you need the server to be outside. 

If you have only a single user, it is probably simpler to avoid the server app and have it be all inside the electron app. 

But I don't know your requirements/context, so it might be better for you continue the path you started.

**Comment by nikhilag** [comment]
I know this is going a little off topic but is it possible to update server code remotely if it's running within the premises of a company? Also is there any disadvantage of running it inside electron vs running it outside? I have also been able to give my server some UI so that logs can be seen, database can be specified, etc. Hence for me electron is working out well. I really hope the load handling capacity of node server doesn't change when it's running outside vs running within a renderer process in an electron app.

**Comment by csepulv** [comment]
That all depends on what they will let you do. Lots of things are possible, but I think you probably need to discuss with them. For example, the simplest thing is for them to let you login remotely instead of some kind of fancier phone-home/self update strategy.

**Comment by MissHax0r** [comment]
You should add a new run script in your Procfile to start the server. This is how we handle running a spring java server that handles our service calls. React server is really meant for serving up your app files for hot deploy. Just make a new script file your Procfile calls.

**Comment by MissHax0r** [comment]
@nikhilag you want to run outside. It is bad design to tightly couple with your client app (electron app). This saves a lot of headaches when you have multiple deployment environments for dev, test, or prod.

**Comment by nikhilag** [comment]
Thanks Kara.

I have two electron apps and one of them is basically for the server. It has a very minimal ui for some settings. Otherwise there is no client side to it. The reason for doing this was to allow clients to install it themselves and allow us to auto update.


On Sep 18, 2017 14:00, Kara Marie Rawson <notifications@github.com> wrote:

@nikhilag<https://github.com/nikhilag> you want to run outside. It is bad design to tightly couple with your client app (electron app). This saves a lot of headaches when you have multiple deployment environments for dev, test, or prod.

**Comment by MissHax0r** [comment]
@nikhilag right, that makes sense if you use electron as a wrapper application to your server, Even though i still would try to avoid smashing your server code directly into the electron app. Having a thin client to handle auto-updating and settings is a great idea. Many games use this architecture to handle auto-updating.. IE just uses electron to download a zip or tar, and have some scripts to call the server from the CLI. Something more fancy would be using sockets to connect your electron to your server.. 

As far as networking and stuff, that really is up to how the firewalls are. Technically you could even configure stuff to use port 80 which most firewalls have open.

As for load, if you dig into the code and read a bunch of comments you will find that calling native file system and other functionality can be hacky. It also adds alot of overhead and makes stuff run wonky.. This is another argument to use an API w/ CLI or API with sockets.

anyways thats just my opinion from experience.. GLHF
